### PR TITLE
feat: added a modal dropdown on medium devices

### LINKED ISSUE #74: Adding a modal or dropdown and showing example questions on mobile screen too
Currently the examples components is only visible on larger screens because it was talking a lot of space in mobile screen 
image

what I'd like to do (only for mobile screen) is add a small button which opens the examples in a modal or a select dropdown on question input itself like this 

iPhone 14 - 1

### PR DESCRIPTION
**Pull request by sboy99**
### Features
- On medium devices there will be a drop down containing question suggesstion
This PR contains following changes
### Changes
- Added AotuComplete component from `@mui`
- Added a useResize hook to caculate window width
- Enabled conditional rendering for AutoComplete & Textsection respective to width
#### Issue
closes #74

### Screenshot
 
Screenshot from 2022-12-25 00-29-05

Screenshot from 2022-12-25 00-30-03

### CODE REVIEW

**Review by Aadarsh805 — CHANGES_REQUESTED** [review]
Okay so it's almost good enough, autocomplete is a good use here but it does not let us put the question ourselves, I still want it to work without the autocomplete, the examples should be examples
using mui autocomplete makes it just a select dropdown doesn't it, i think you got what I'm saying
It still works though, it still takes question out of examples, but it just doesn't show there
see if you can make it do that

**Comment by Aadarsh805** [comment]
@sboy99 just add `freesolo` to the autocomplete and it'll work fine, commit this change on this same branch and I'll merge it
great job

**Comment by Aadarsh805** [comment]
> ge it great job image

I did it no worries, let me merge and try it in deployment

**Comment by sboy99** [comment]
Yeah that's why I was talking about headlessui. In headlessui they have a combobox component that let us define query and also the selection, you can definitely give a sight.
However, to be honest I never tried mui, it was first time but still it was a amazing experience. I think the project needs to be more strict, cause there are so many unused imports as well as one file has '.jsx' extension while its using typescript.

**Comment by Aadarsh805** [comment]
> 

I just didn't want to increase the bundle size by adding another library, yeah I know we built this very carelessly, there is a lot of cleanup to do

**Pull request merged**
