### PR TITLE
[add]:login with twitter btn

### LINKED ISSUE #11: Create a login with twitter button on Navbar along side github button for desktop screen only

### PR DESCRIPTION
**Pull request by stephenokyere233**
Fixes #11 
- Added login with twitter button on the Navbar

### CODE REVIEW

**Review by Aadarsh805 — APPROVED** [review]
this is perfect

**Comment by Aadarsh805** [comment]
@stephenokyere233 where do you say it should go on smaller screen sizes, priority still is the Github star button, because signing will be optional

**Comment by stephenokyere233** [comment]
On smaller screens is hard to place it on the navbar, I'll look at the whole website again and get back to you

**Comment by stephenokyere233** [comment]
I think i could go side by side with the try it out button or take the login to comment's place that's from vercel so it's not on the original site @Aadarsh805

**Comment by Aadarsh805** [comment]
@stephenokyere233 Nah we can't do it on the page because it has to be seen as very optional, can do side by side GitHub button, making both extra small
I'm only adding login so that when the feature to capture your generated answer is done, we can have the option to save to your profile, for that login will be required, so it has to be very optional

**Comment by Aadarsh805** [comment]
@stephenokyere233 we can show the login button directly when a user selects to save a response to profile, instead of keeping on navbar, how's that

**Comment by stephenokyere233** [comment]
@Aadarsh805 okay I'll see if making them smaller will look good or instead of writing "login with Twitter" I'll just say login+ the Twitter logo

**Comment by Aadarsh805** [comment]
> @Aadarsh805 okay I'll see if making them smaller will look good or instead of writing "login with Twitter" I'll just say login+ the Twitter logo

yeah that'll work fine, I'll finish the actual login process then we can do the buttons and all

**Comment by stephenokyere233** [comment]
@Aadarsh805 That will be nice I'll checkout other issues i could work on

**Pull request merged**
